// <auto-generated />
using System;
using System.Collections.Generic;
using DelicutTelegramBot.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DelicutTelegramBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321203608_AddMacroGoals")]
    partial class AddMacroGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.PendingSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Carb")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("DeliveryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision");

                    b.Property<double>("Kcal")
                        .HasColumnType("double precision");

                    b.Property<string>("MealCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariantProtein")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PendingSelections");
                });

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.SelectionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("SelectedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariantProtein")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WasUserChoice")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DishId", "SelectedDate", "MealCategory")
                        .IsUnique();

                    b.ToTable("SelectionHistories");
                });

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DelicutCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("DelicutEmail")
                        .HasColumnType("text");

                    b.Property<string>("DelicutSubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("DelicutToken")
                        .HasColumnType("text");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CarbGoalGrams")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FatGoalGrams")
                        .HasColumnType("double precision");

                    b.Property<bool>("PreferHistory")
                        .HasColumnType("boolean");

                    b.Property<double?>("ProteinGoalGrams")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("StopWords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.PendingSelection", b =>
                {
                    b.HasOne("DelicutTelegramBot.Models.Domain.User", "User")
                        .WithMany("PendingSelections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.SelectionHistory", b =>
                {
                    b.HasOne("DelicutTelegramBot.Models.Domain.User", "User")
                        .WithMany("SelectionHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.UserSettings", b =>
                {
                    b.HasOne("DelicutTelegramBot.Models.Domain.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("DelicutTelegramBot.Models.Domain.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DelicutTelegramBot.Models.Domain.User", b =>
                {
                    b.Navigation("PendingSelections");

                    b.Navigation("SelectionHistories");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
